# Generated by Django 5.2.4 on 2025-08-03 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="White Raven Pourhouse",
                        help_text="Business name",
                        max_length=100,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="The Best Little Pour House in Felton",
                        help_text="Business tagline or slogan",
                        max_length=200,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Full business address including city, state, zip"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Business contact email", max_length=254
                    ),
                ),
                (
                    "hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operating hours by day of week. Format: {'monday': {'open': '07:00', 'close': '19:00', 'closed': false}, ...}",
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(
                        blank=True,
                        help_text="Instagram username (without @)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the business for the homepage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Information",
                "verbose_name_plural": "Business Information",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Visitor's full name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Visitor's email address", max_length=254
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("menu", "Menu Question"),
                            ("hours", "Hours/Location"),
                            ("event", "Event/Catering"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="general",
                        help_text="Subject category for the inquiry",
                        max_length=50,
                    ),
                ),
                (
                    "custom_subject",
                    models.CharField(
                        blank=True,
                        help_text="Custom subject line if 'Other' is selected",
                        max_length=200,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="The visitor's message or inquiry"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the form was submitted"
                    ),
                ),
                (
                    "responded",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as True when you've responded to this inquiry",
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the response or follow-up",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
