# Generated by Django 5.2.4 on 2025-08-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinfo",
            name="special_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Special hours for specific dates. Format: {'2024-12-25': {'closed': true, 'note': 'Christmas Day'}, '2024-07-04': {'open': '08:00', 'close': '16:00', 'note': 'Independence Day - Limited Hours'}}",
            ),
        ),
    ]
