# Generated by Django 5.2.4 on 2025-08-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessinfo_special_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for the homepage (recommended size: 1200x600px)', null=True, upload_to='business/hero/'),
        ),
    ]
