# Generated by Django 5.2.4 on 2025-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businessinfo_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='copyright_text',
            field=models.CharField(default='White Raven Pourhouse', help_text='Business name for copyright notice', max_length=200),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook page URL (e.g., https://facebook.com/whiteravenpourhouse)'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='footer_tagline',
            field=models.CharField(default='Made with ❤ in Felton, CA', help_text='Tagline shown in website footer', max_length=200),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Full Instagram page URL (e.g., https://instagram.com/white_raven_pour_house)'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='meta_description',
            field=models.TextField(default='White Raven Pourhouse - The Best Little Pour House in Felton. Serving exceptional coffee and creating memorable experiences in Felton, CA.', help_text='SEO meta description for the website'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Welcome message for homepage (falls back to default if empty)'),
        ),
    ]
