# Generated by Django 5.2.4 on 2025-08-04 16:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_businessinfo_copyright_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="White Raven Theme",
                        help_text="Theme name for identification",
                        max_length=100,
                    ),
                ),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        default="#6f4f28",
                        help_text="Primary brand color (used for buttons, links)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#8b7355",
                        help_text="Secondary color (used for accents, hover states)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "accent_color",
                    colorfield.fields.ColorField(
                        default="#d4af37",
                        help_text="Accent color (used for highlights, CTAs)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "text_color",
                    colorfield.fields.ColorField(
                        default="#2c3e50",
                        help_text="Main text color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "text_light",
                    colorfield.fields.ColorField(
                        default="#6c757d",
                        help_text="Light text color (for descriptions, captions)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "background_color",
                    colorfield.fields.ColorField(
                        default="#ffffff",
                        help_text="Main background color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "background_secondary",
                    colorfield.fields.ColorField(
                        default="#f8f9fa",
                        help_text="Secondary background (for sections, cards)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "navbar_bg",
                    colorfield.fields.ColorField(
                        default="#ffffff",
                        help_text="Navigation bar background color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "navbar_text",
                    colorfield.fields.ColorField(
                        default="#2c3e50",
                        help_text="Navigation bar text color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "navbar_hover",
                    colorfield.fields.ColorField(
                        default="#6f4f28",
                        help_text="Navigation bar hover color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "button_primary_bg",
                    colorfield.fields.ColorField(
                        default="#6f4f28",
                        help_text="Primary button background",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "button_primary_text",
                    colorfield.fields.ColorField(
                        default="#ffffff",
                        help_text="Primary button text color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "button_secondary_bg",
                    colorfield.fields.ColorField(
                        default="#8b7355",
                        help_text="Secondary button background",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "button_secondary_text",
                    colorfield.fields.ColorField(
                        default="#ffffff",
                        help_text="Secondary button text color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "menu_decoration_image",
                    models.ImageField(
                        blank=True,
                        help_text="Decorative image for menu page (replaces the white stats box). Recommended size: 400x300px",
                        null=True,
                        upload_to="site_theme/menu/",
                    ),
                ),
                (
                    "menu_decoration_alt_text",
                    models.CharField(
                        blank=True,
                        default="White Raven Pourhouse decoration",
                        help_text="Alt text for the menu decoration image (for accessibility)",
                        max_length=200,
                    ),
                ),
                (
                    "footer_bg",
                    colorfield.fields.ColorField(
                        default="#2c3e50",
                        help_text="Footer background color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "footer_text",
                    colorfield.fields.ColorField(
                        default="#ffffff",
                        help_text="Footer text color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "footer_link",
                    colorfield.fields.ColorField(
                        default="#d4af37",
                        help_text="Footer link color",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this theme is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Theme",
                "verbose_name_plural": "Site Themes",
                "ordering": ["-created_at"],
            },
        ),
    ]
