# Generated by Django 5.2.4 on 2025-08-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitetheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessinfo",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Hero image for the homepage (recommended size: 1200x600px)",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="sitetheme",
            name="menu_decoration_image",
            field=models.ImageField(
                blank=True,
                help_text="Decorative image for menu page (replaces the white stats box). Recommended size: 400x300px",
                null=True,
                upload_to="",
            ),
        ),
    ]
