# Generated by Django 5.2.4 on 2025-08-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_businessinfo_hero_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinfo",
            name="about_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for the About page story section (recommended size: 600x400px)",
                null=True,
                upload_to="",
            ),
        ),
    ]
