# Generated by Django 5.2.4 on 2025-08-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_businessinfo_about_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinfo",
            name="location_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for the Location page header (recommended size: 600x400px)",
                null=True,
                upload_to="",
            ),
        ),
    ]
