# Generated by Django 5.2.4 on 2025-08-03 00:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Internal employee ID (auto-generated)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Employee contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        help_text="Emergency contact full name", max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        help_text="Emergency contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("shift_lead", "Shift Lead"),
                            ("barista", "Barista"),
                            ("cashier", "Cashier"),
                            ("kitchen", "Kitchen Staff"),
                            ("part_time", "Part-time"),
                            ("intern", "Intern"),
                        ],
                        default="barista",
                        help_text="Employee role/position",
                        max_length=20,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        help_text="Current employment status",
                        max_length=15,
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(help_text="Date when employee was hired"),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when employment ended (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "hourly_wage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly wage rate",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this employee"
                    ),
                ),
                (
                    "can_open",
                    models.BooleanField(
                        default=False,
                        help_text="Employee is authorized to open the store",
                    ),
                ),
                (
                    "can_close",
                    models.BooleanField(
                        default=False,
                        help_text="Employee is authorized to close the store",
                    ),
                ),
                (
                    "can_handle_cash",
                    models.BooleanField(
                        default=True,
                        help_text="Employee is authorized to handle cash transactions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Django user account for this employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the scheduled shift")),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Break duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening Shift"),
                            ("mid", "Mid Shift"),
                            ("closing", "Closing Shift"),
                            ("full", "Full Day"),
                            ("split", "Split Shift"),
                        ],
                        default="mid",
                        help_text="Type of shift",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("called_in_sick", "Called In Sick"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        help_text="Current status of this shift",
                        max_length=15,
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Actual time employee started (if different from scheduled)",
                        null=True,
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Actual time employee finished (if different from scheduled)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this shift"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Who created this schedule entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee assigned to this shift",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "ordering": ["date", "start_time"],
                "unique_together": {("employee", "date", "start_time")},
            },
        ),
    ]
