# Generated by Django 5.2.4 on 2025-08-03 04:38

import menu.fields
import menu.utils.image_processing
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=menu.fields.MenuImageField(
                blank=True,
                help_text="Upload an image for this menu item. Images will be automatically optimized for web display.",
                upload_to=menu.utils.image_processing.get_image_upload_path,
            ),
        ),
    ]
